# Generated by Django 4.0.3 on 2022-09-02 11:29

from django.db import migrations, models
import django.utils.timezone
import schoolproject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('adopter_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('phone', models.CharField(error_messages={'required': 'Please enter phone number'}, max_length=20)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'required': 'Please enter username'}, max_length=64, unique=True)),
                ('email', models.EmailField(error_messages={'required': 'Please enter email'}, max_length=255)),
                ('phone', models.CharField(error_messages={'required': 'Please enter phone number'}, max_length=20)),
                ('password', models.CharField(error_messages={'required': 'Please enter password'}, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Whelp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=schoolproject.models.get_file_path)),
                ('user', models.CharField(max_length=64)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
